### ISSUE TITLE
some pictures are too big

### ISSUE THREAD

**Issue by qianzhouyi2** [mathllm/MATH-V#4]
The image for question ID 2467 and 2955 are too large compared with other pictures
using the standard qwen2-7b vl setting will result in a100-80g out of memory

**Comment by scikkk** [comment]
Thank you for your feedback! However, there are actually more than 30 images that are larger than (in width/height/file size) the ones for question IDs 2467 and 2955. Specifically, image 2467 is 178 KB, and image 2955 is 256 KB, both of which are within a reasonable size range. Let me know if you have any other concerns! (:
